Repository CTSRD-CHERI/cheribsd, pull requests merged in 2020-05, with the labels that each got.

#436 Fix CTF pointer overrun (in userland)
  cddl/contrib/opensolaris/common/ctf/ctf_lookup.c
Labels: bug

#440 Fix kldxref cheri-related issue
  usr.sbin/kldxref/ef_mips.c
Labels: CheriCCompat, bug

#483 Add cheri branch opcodes and fix MipsEmulateBranch
  sys/mips/include/mips_opcode.h
  sys/mips/mips/trap.c
Labels: ALWAYS-JENKINS

#505 Fix assertion in calloc
  contrib/jemalloc/src/jemalloc.c
Labels: NO-JENKINS

#471 Fix ioctl arguments behaviour when size is zero
  lib/libc/sys/ioctl.c
Labels: bug
