Repository CTSRD-CHERI/cheribsd, pull requests merged in 2021-12, with the labels that each got.

#1185 Remove upstream CODEOWNERS file.
  .github/CODEOWNERS
Labels: NO-JENKINS

#1137 Document the current process for merging from FreeBSD
  CHERI-UPDATING.md
Labels: NO-JENKINS, ready-to-land

#1191 recvfrom: reduce diffs to upstream
  sys/kern/uipc_syscalls.c
Labels: ready-to-land

#1192 syscallarg_t: remove layer of typedef indirection
  sys/sys/types.h
Labels: ready-to-land

#1199 libc: Fix bogus race handling code in emutls_index
  lib/libc/gen/emutls.c
Labels: ready-to-land

#1200 re: Avoid subobject overread when setting IDRn
  sys/dev/re/if_re.c
Labels: ready-to-land
